big chungus
• ~/.tags target added to ./Makefile
• bin/save simplified
• bin/shodmenu simplified (icons are no more)
• bin/startmenu simplified
• i hate vim

diff --git a/bin/save b/bin/save
--- a/bin/save
+++ b/bin/save
@@ -9,58 +9,22 @@
 action=
 exitval=0
 
-usage() {
-	printf "usage: %s [-abfin] file...\n" "${0##*/}" >&2
-	exit 2
-}
-
-warn() {
-	fmt="$1"
-	shift
-	printf "%s: $fmt\n" "${0##*/}" "$@" >&2
-}
-
-isvalid() {
-	case "$1" in
-	(""|[[:space:]]*|*[[:space:]])
-		false
-		;;
-	(*)
-		true
-	;;
-	esac
-}
-
-genpath() {
-	basename="${1##*/}"
-	dirname="${1%"$basename"}"
-	body="${basename%.*}"
-	ext="${basename##"$body"}"
-	unset -v i p
-	while test -e "$dirname$body$p$i$ext"
-	do
-		p="_"
-		if test -z "$i"
-		then
-			i=1
-		else
-			i="$((i + 1))"
-		fi
-	done
-	printf "%s" "$dirname$body$p$i$ext"
-}
-
 while getopts abfin opt
 do case "$opt" in
 ([abfin])
 	action="$opt"
 	;;
 (*)
-	usage
+	set --
+	break
 	;;
 esac done
 shift "$((OPTIND - 1))"
-test "$#" -eq 0 && usage
+if test "$#" -eq 0
+then
+	echo "usage: save [-abfin] file..." >&2
+	exit 2
+fi
 
 temp="$(mktemp -p "$(dirname "$1")")" || exit
 trap 'rm -f -- "$temp"' EXIT
@@ -70,18 +34,39 @@ for file
 do
 	shift
 
-	if ! isvalid "$file"
-	then
-		warn "%s: improper file name" "$file"
+	case "$file" in
+	(""|[[:space:]]*|*[[:space:]])
+		printf "save: %s: Invalid argument\n" "$file" >&2
 		exitval=1
-	fi
+		continue
+		;;
+	esac
+
+	unique="$(
+		basename="${1##*/}"
+		dirname="${1%"$basename"}"
+		body="${basename%.*}"
+		ext="${basename##"$body"}"
+		unset -v i p
+		while test -e "$dirname$body$p$i$ext"
+		do
+			p="_"
+			if test -z "$i"
+			then
+				i=1
+			else
+				i="$((i + 1))"
+			fi
+		done
+		printf "%s" "$dirname$body$p$i$ext"
+	)"
 
 	if test -e "$file"
 	then
 		ans="$action"
 		if test -z "$action"
 		then
-			warn "%s: File exists" "$file"
+			printf "save: %s: File exists\n" "$file" >&2
 			exitval=1
 			continue
 		elif test "$action" = "i"
@@ -100,7 +85,7 @@ do
 			;;
 		(b)
 			# backup existing file
-			mv -- "$file" "$(genpath "$file")" || exit
+			mv -- "$file" "$unique" || exit
 			;;
 		(f)
 			# overwrite existing file
@@ -108,7 +93,7 @@ do
 			;;
 		(n)
 			# save as new file, if exists
-			file="$(genpath "$file")"
+			file="$unique"
 			;;
 		(?)
 			continue
diff --git a/lib/kshrc b/lib/kshrc
--- a/lib/kshrc
+++ b/lib/kshrc
@@ -1,6 +1,5 @@
 #!/bin/ksh
 #
-# Usage: . ~/.kshrc
 # Initialization script for interactive ksh(1) sessions.
 # Depends only on OpenBSD base utilities.
 #
@@ -11,36 +10,31 @@
 . /etc/ksh.kshrc
 . "$HOME/.profile"
 
-# run given command on background
-run() (
-	trap : HUP
-	exec 1>/dev/null 2>/dev/null 0</dev/null
-	exec "$@" &
-)
+# reload a running shell session
+reload() {
+	. ~/.kshrc
+}
 
-# run given command with doas; or re-run previous command with doas(1)
-fuck() {
-	test "$#" -gt 0 && {
-		doas -- "$@" 
-		return
-	}
-	typeset n="$(
-		fc -l 1 |
-		sed -En '
-			/^[[:digit:]]+[[:space:]]+fuck/!h
-			${
-				g
-				s/[[:space:]].*//
-				p
-			}
-		'
-	)"
-	if test -z "$n"
-	then
-		echo "ksh: fuck: no command to retry" >&2
-		return 127
-	fi
-	fc -e "sed -i '/^doas/!s/^/doas /'" "$n"
+# extend doas to re-run previous command on doas when no argument is given
+doas() {
+	case "$#" in
+	(0)
+		fc -e "sed -i '/^doas/!s/^/doas /'" "$(
+			fc -l 1 |
+			sed -En '
+				/^[[:digit:]]+[[:space:]]+doas/!h
+				${
+					g
+					s/[[:space:]].*//
+					p
+				}
+			'
+		)"
+		;;
+	(*)
+		command doas "$@" 
+		;;
+	esac
 }
 
 # extend cd with two forms for going up; and set completions for make(1)
@@ -71,7 +65,7 @@ cd() {
 	command cd "$1" >/dev/null || return 1
 	set -A complete_make -- $(
 		exec 2>/dev/null
-		make -qp |
+		timeout 1s make -qp |
 		sed -n '/^[A-Za-z][^ :]* *:/{s/\([^: ]*\).*/\1/p;}'
 	)
 	case "$PWD/" in
@@ -85,106 +79,232 @@ cd() {
 	return 0
 }
 
+# Further functions do not modify the currently running shell session.
+#
+# From now on, i define functions in a subshell like `f()(...)`, rather
+# than in the current shell like `f(){ ...;}`.  Thus, all variables are
+# local; and built-ins like exec, exit, and trap behave like they would
+# in a shell script.
+
+# spawn command in background, ignoring output
+nohup() (
+	trap : HUP
+	exec 1>/dev/null 2>/dev/null 0</dev/null
+	exec "$@" &
+)
+
 # read stdin into temp file; run args on file; write file to stdout
-pee() {
+pee() (
 	test "$#" -eq 0 && set -- cat
-	typeset tmp="$(mktemp)"
-	test -n "$tmp" && test -w "$tmp" && test -r "$tmp" || {
-		rm "$tmp" 2>/dev/null
+	temp=
+	trap '\rm -f -- "$temp"' EXIT
+	temp="$(mktemp)"
+	test -n "$temp" && test -w "$temp" && test -r "$temp" || {
+		rm "$temp" 2>/dev/null
 		return 1
 	}
-	cat >"$tmp" && "$@" "$tmp" <>/dev/tty >&0 2>&0 && cat "$tmp"
-	rm "$tmp" 2>/dev/null
-}
+	cat >"$temp" && "$@" "$temp" <>/dev/tty >&0 2>&0 && cat "$temp"
+)
 
-# colorize output of compilers, builders and diff'ers
-colorize() {
-	test "$#" -eq 0 && return
-	if test -t 1 && test -t 2
-	then
-		"$@" 2>&1 | awk -v cmd="$1" '
-		BEGIN {
-			REVERSE = "\x1b[7m"
-			RED = "\x1b[31m"
-			GREEN = "\x1b[32m"
-			YELLOW = "\x1b[33m"
-			BLUE = "\x1b[34m"
-			PURPLE = "\x1b[35m"
-			RESET = "\x1b[0m"
-		}
-		$1 == "@@" && $4 == "@@" {
-			$1 = BLUE "@@"
-			$4 = "@@" RESET
-			print
-			next
-		}
-		$1 == "+++" {
-			$1 = GREEN $1 RESET
-			print
-			next
-		}
-		$1 == "---" {
-			$1 = RED $1 RESET
-			print
-			next
-		}
-		substr($0, 1, 1) == "+" {
-			printf "%s+%s%s\n", GREEN, RESET, substr($0, 2)
-			next
-		}
-		substr($0, 1, 1) == "-" {
-			printf "%s-%s%s\n", RED, RESET, substr($0, 2)
-			next
-		}
-		substr($1, length($1), 1) == ":" && $2 == "error:" {
-			$2 = RED $2 RESET
-			print
-			next
-		}
-		substr($1, length($1), 1) == ":" && $2 == "warning:" {
-			$2 = PURPLE $2 RESET
-			print
-			next
-		}
-		substr($1, length($1), 1) == ":" && $2 == "note:" {
-			$2 = BLUE $2 RESET
-			print
-			next
-		}
-		1'
-	else
-		"$@"
-	fi
-}
+# saves stdin into FILE; flags tells what to do when FILE exists.
+save() (
+	action=
+	exitval=0
 
-# check if command exists and, if so, set its completable arguments
-complete() {
-	typeset cmd="$1"
-	shift
-	command -v "$cmd" >/dev/null || return
-	case "$1" in
-	([1-9])
-		typeset arg="_$1"
-		shift
+	while getopts abfin opt
+	do case "$opt" in
+	([abfin])
+		action="$opt"
 		;;
 	(*)
-		typeset arg=""
-		shift
+		set --
+		break
 		;;
-	esac
-	set -A complete_"${cmd}${arg}" -- "$@"
-}
+	esac done
+	shift "$((OPTIND - 1))"
+	if test "$#" -eq 0
+	then
+		echo "usage: save [-abfin] file..." >&2
+		exit 2
+	fi
 
+	temp="$(mktemp -p "$(dirname "$1")")" || exit
+	trap 'rm -f -- "$temp"' EXIT
+	cat >"$temp" || exit
+
+	for file
+	do
+		shift
+
+		case "$file" in
+		(""|[[:space:]]*|*[[:space:]])
+			printf "save: %s: Invalid argument\n" "$file" >&2
+			exitval=1
+			continue
+			;;
+		esac
+
+		unique="$(
+			basename="${1##*/}"
+			dirname="${1%"$basename"}"
+			body="${basename%.*}"
+			ext="${basename##"$body"}"
+			unset -v i p
+			while test -e "$dirname$body$p$i$ext"
+			do
+				p="_"
+				if test -z "$i"
+				then
+					i=1
+				else
+					i="$((i + 1))"
+				fi
+			done
+			printf "%s" "$dirname$body$p$i$ext"
+		)"
+
+		if test -e "$file"
+		then
+			ans="$action"
+			if test -z "$action"
+			then
+				printf "save: %s: File exists\n" "$file" >&2
+				exitval=1
+				continue
+			elif test "$action" = "i"
+			then
+				printf "%s: File exists\n" "$file"
+				printf "\t(B)ackup,"
+				printf " (F)orce overwrite,"
+				printf " or save as (N)ew file?\n"
+				read -r ans </dev/tty
+			fi >&2
+			case "$ans" in
+			(a)
+				# append into existing file
+				cat <"$temp" >>"$file"
+				continue
+				;;
+			(b)
+				# backup existing file
+				mv -- "$file" "$unique" || exit
+				;;
+			(f)
+				# overwrite existing file
+				rm -- "$file"
+				;;
+			(n)
+				# save as new file, if exists
+				file="$unique"
+				;;
+			(?)
+				continue
+				;;
+			esac
+		fi
+		if test "$#" -eq 0
+		then
+			mv -- "$temp" "$file" || exitval=1
+		else
+			cp -- "$temp" "$file" || exitval=1
+		fi
+	done
+	rm -f "$temp"
+	exit "$exitval"
+)
+
+# colorize output of compilers, builders and diff'ers
+colorize() (
+	test "$#" -eq 0 && return
+	command "$@" 2>&1 | awk -v cmd="$1" '
+	BEGIN {
+		REVERSE = "\x1b[7m"
+		RED = "\x1b[31m"
+		GREEN = "\x1b[32m"
+		YELLOW = "\x1b[33m"
+		BLUE = "\x1b[34m"
+		PURPLE = "\x1b[35m"
+		RESET = "\x1b[0m"
+	}
+	$1 == "@@" && $4 == "@@" {
+		$1 = BLUE "@@"
+		$4 = "@@" RESET
+		print
+		next
+	}
+	$1 == "+++" {
+		$1 = GREEN $1 RESET
+		print
+		next
+	}
+	$1 == "---" {
+		$1 = RED $1 RESET
+		print
+		next
+	}
+	substr($0, 1, 1) == "+" {
+		printf "%s+%s%s\n", GREEN, RESET, substr($0, 2)
+		next
+	}
+	substr($0, 1, 1) == "-" {
+		printf "%s-%s%s\n", RED, RESET, substr($0, 2)
+		next
+	}
+	substr($1, length($1), 1) == ":" && $2 == "error:" {
+		$2 = RED $2 RESET
+		print
+		next
+	}
+	substr($1, length($1), 1) == ":" && $2 == "warning:" {
+		$2 = PURPLE $2 RESET
+		print
+		next
+	}
+	substr($1, length($1), 1) == ":" && $2 == "note:" {
+		$2 = BLUE $2 RESET
+		print
+		next
+	}
+	1'
+)
+
+# these need to be functions; aliases would break when colorize() is not defined
+got() { test "$1" = "diff" && colorize got "$@" || command got "$@" ; }
+make() { colorize make "$@" ; }
+diff() { colorize diff -up "$@" ; }
+cc() { colorize cc "$@" ; }
+
+# completions; ignore error when defining them
 {
-	complete sysctl $(sysctl | sed 's,[= ].*,,')
-	complete rcctl 1 disable enable get ls order set restart start stop
-	complete rcctl 2 $(rcctl ls all)
-	complete vmd 1 console load reload start stop reset status send receive
-	complete vmd $(vmctl status | awk '!/NAME/{print $NF}')
-	complete got 1 add backout blame branch cat checkout cherrypick \
-	clone commit diff fetch histedit import info init integrate log \
-	merge patch rebase ref remove revert send stage status tag tree \
-	unstage update
+	set -A complete_sysctl \
+		$(sysctl | sed 's,[= ].*,,')
+	set -A complete_rcctl \
+		$(rcctl ls all)
+	set -A complete_vmctl \
+		$(vmctl status | awk '!/NAME/{print $NF}')
+	set -A complete_rcctl_1 \
+		disable enable get ls order set restart start stop
+	set -A complete_vmctl_1 \
+		console create load log pause receive reload reset \
+		send show start status stop unpause wait
+	set -A complete_got_1 \
+		add backout blame branch cat checkout cherrypick clone \
+		commit diff fetch histedit import info init integrate \
+		log merge patch rebase ref remove revert send stage \
+		status tag tree unstage update
+	set -A complete_mpc_1 \
+		add addplaylist albumart cdprev channels clear \
+		clearerror clearplaylist consume crop crossfade current \
+		del delpart delplaylist disable enable find findadd idle \
+		idleloop insert list listall listneighbors load ls \
+		lsdirs lsplaylists makepart mixrampdb mixrampdelay mount \
+		move moveoutput moveplaylist next outputs outputset \
+		partitions pause pause-if-playing play playlist prev \
+		prio queued random readpicture renplaylist repeat \
+		replaygain rescan rm save search searchadd searchplay \
+		seek seekthrough sendmessage shuffle single stats \
+		sticker stop subscribe toggle toggleoutput unmount \
+		update version volume waitmessage
 } 2>/dev/null
 
 # force emacs[1] keybindings even when $VISUAL is set to a vi-like editor
@@ -215,30 +335,20 @@ alias od='od -cAx'
 # human-readable sizes
 alias df='df -h'
 alias du='du -hc'
+alias ls='ls -1Fh'
+alias disklabel='disklabel -h'
 
 # lazyman aliases
-alias ls='ls -1Fh'
 alias lc='ls -C'
 alias ll='ls -l'
 alias calc='bc -l'
-alias diff='diff -up'
 
 # commands with command as argument (for futher alias expension)
 alias xargs='tr "\n" "\0" | xargs -0 '
 alias doas='doas '
-alias fuck='fuck '
+alias fuck='doas '
 alias timeout='timeout '
 alias apply='apply '
-
-# grep
-alias grep='egrep'
-alias fgrep='fgrep -i'
-
-# colorization
-alias got='colorize got'
-alias make='colorize make'
-alias cc='colorize cc'
-alias diff='colorize diff'
 
 # pipeline utils
 # PROTIP: Running "doas foo >/root/file" does not write into /root/file.
@@ -261,8 +371,8 @@ alias makemake='make'
 # prompt is "\n HOST ❯ " (red if root; HOST if ssh; also set window title)
 PS1='$(
 	case "$(id -u)" in
-		(0) color="31m" ;;
-		(*) color="1m"    ;;
+		(1000) user="" ;;
+		(*) user="$USER@"    ;;
 	esac
 	case "$PWD/" in
 		("$HOME"/*) cwd="~${PWD#"${HOME}"}" ;;
@@ -271,16 +381,12 @@ PS1='$(
 	term='"$(tty | sed s,^/dev/,,)"'
 	host='"${SSH_CONNECTION:+"$(hostname)"}"'
 	title="$host${host:+:}$cwd - $term"
-	printf "\e[0m\e]0;%s\a\n%s \e[%s❯ \e[0m" "$title" "$host" "$color"
+	printf "\e[0m\e]0;%s\a\n\e[31m%s%s ❯ \e[0m" "$title" "$user" "$host"
 )'
 
 # 2nd prompt is " ❮ " (red if root, white otherwise)
 PS2="$(
-	case "$(id -u)" in
-		(0) color="31m" ;;
-		(*) color="1m"    ;;
-	esac
-	printf "\e[0m \e[%s❮ \e[0m" "$color"
+	printf "\e[0m \e[31m❮ \e[0m"
 )"
 
 # print last command's exit status, if non-zero
